### ISSUE TITLE
本番環境でUnicorn起動するとNoMethodError

### ISSUE THREAD

**Issue by tyamap** [tyamap/ganva-app#81]
```
bundle exec unicorn -c config/unicorn.rb -p 3000 -E production
```

実行時、unicorn.logに以下のログが出力され、サーバ起動失敗する。  

```
I, [2020-05-04T16:21:34.999779 #9]  INFO -- : Refreshing Gem list
bundler: failed to load command: unicorn (/usr/local/bundle/bin/unicorn)
NoMethodError: undefined method `index' for User::AchievementsController:Class
  /ganva-app/app/controllers/user/achievements_controller.rb:2:in `<class:AchievementsController>'
  /ganva-app/app/controllers/user/achievements_controller.rb:1:in `<main>'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
  /usr/local/bundle/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/kernel.rb:16:in `require'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:351:in `const_get'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:351:in `block (2 levels) in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:685:in `block in ls'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:682:in `foreach'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:682:in `ls'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:346:in `block in eager_load'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:338:in `synchronize'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:338:in `eager_load'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:449:in `each'
  /usr/local/bundle/gems/zeitwerk-2.2.2/lib/zeitwerk/loader.rb:449:in `eager_load_all'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/application/finisher.rb:122:in `block in <module:Finisher>'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `instance_exec'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:32:in `run'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
  /usr/local/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/local/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /usr/local/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/local/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /usr/local/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/initializable.rb:60:in `run_initializers'
  /usr/local/bundle/gems/railties-6.0.2.1/lib/rails/application.rb:363:in `initialize!'
  /ganva-app/config/environment.rb:5:in `<top (required)>'
  config.ru:4:in `require_relative'
  config.ru:4:in `block in <main>'
  /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:125:in `instance_eval'
  /usr/local/bundle/gems/rack-2.2.2/lib/rack/builder.rb:125:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /usr/local/bundle/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `eval'
  /usr/local/bundle/gems/unicorn-5.5.4/lib/unicorn.rb:54:in `block in builder'
  /usr/local/bundle/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:794:in `build_app!'
  /usr/local/bundle/gems/unicorn-5.5.4/lib/unicorn/http_server.rb:141:in `start'
  /usr/local/bundle/gems/unicorn-5.5.4/bin/unicorn:128:in `<top (required)>'
  /usr/local/bundle/bin/unicorn:23:in `load'
  /usr/local/bundle/bin/unicorn:23:in `<top (required)>'
```
bootsnapでなぜかachievements_controllerが呼び出される。  
achivement機能は未実装のため、本番サーバで該当のコントローラーファイルを削除して再起動するとエラーは解消された。  
今後achievement機能を本番に実装する際は、コントローラ名の変更が必要？ しかし謎。

**Comment by tyamap** [comment]
bootsnapのバージョンアップ？  gemのソースファイルを見てみる？

**Comment by tyamap** [comment]
def が抜けてました
